require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("../../js/admin/bootstrap_custom")
require("trix")
require("../../js/admin/main")
require('../../scss/admin/manifest.scss')